xvidencoder: com_zxelec_encoder_XvidEncoder.cpp
        g++ -g -o libxvidencoder.so -I/usr/java/jdk1.6.0/include -I/usr/java/jdk1.6.0/include/linux/ -fPIC -shared com_zxelec_encoder_XvidEncoder.cpp encoder/XvidEncoder.cpp -Wl,-rpath,./ encoder/libxvidcore.so.4



clean:
        rm XvidEncoder -rf
