/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zxelec_encoder_XvidEncoder */

#ifndef _Included_com_zxelec_encoder_XvidEncoder
#define _Included_com_zxelec_encoder_XvidEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zxelec_encoder_XvidEncoder
 * Method:    _XvidEncoder
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_zxelec_encoder_XvidEncoder__1XvidEncoder
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_zxelec_encoder_XvidEncoder
 * Method:    _destoryXvidEncoder
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_zxelec_encoder_XvidEncoder__1destoryXvidEncoder
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_zxelec_encoder_XvidEncoder
 * Method:    _init
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_zxelec_encoder_XvidEncoder__1init
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_zxelec_encoder_XvidEncoder
 * Method:    _stop
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zxelec_encoder_XvidEncoder__1stop
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_zxelec_encoder_XvidEncoder
 * Method:    _encode
 * Signature: (I[B[BIIIII)I
 */
JNIEXPORT jint JNICALL Java_com_zxelec_encoder_XvidEncoder__1encode
  (JNIEnv *, jobject, jint, jbyteArray, jbyteArray, jint, jint, jint, jint, jint);

/*
 * Class:     com_zxelec_encoder_XvidEncoder
 * Method:    _removedivxp
 * Signature: (I[BI)V
 */
JNIEXPORT void JNICALL Java_com_zxelec_encoder_XvidEncoder__1removedivxp
  (JNIEnv *, jobject, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
